# Generated by Django 5.1.1 on 2025-08-26 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("topic", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "presentation",
                    models.FileField(
                        blank=True, null=True, upload_to="lectures/presentations/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_published", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lectures",
                        to="courses.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_lectures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "lecture",
                "verbose_name_plural": "lectures",
                "ordering": ["course", "order"],
            },
        ),
        migrations.CreateModel(
            name="HomeworkAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("max_score", models.PositiveIntegerField(default=100)),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="assignments/attachments/"
                    ),
                ),
                ("allow_multiple_submissions", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_homework_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homework_assignments",
                        to="lectures.lecture",
                    ),
                ),
            ],
            options={
                "verbose_name": "homework assignment",
                "verbose_name_plural": "homework assignments",
                "ordering": ["lecture", "due_date"],
            },
        ),
        migrations.AddIndex(
            model_name="lecture",
            index=models.Index(
                fields=["course", "order"], name="lectures_le_course__9ba49a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lecture",
            constraint=models.UniqueConstraint(
                fields=("course", "slug"), name="unique_lecture_slug_per_course"
            ),
        ),
        migrations.AddIndex(
            model_name="homeworkassignment",
            index=models.Index(
                fields=["lecture", "due_date"], name="lectures_ho_lecture_2e94aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="homeworkassignment",
            constraint=models.UniqueConstraint(
                fields=("lecture", "title"), name="unique_homework_title_per_lecture"
            ),
        ),
    ]
