# Generated by Django 5.1.1 on 2025-08-31 22:49

import common.field_validators.advanced_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeworkassignment",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="assignments/attachments/",
                validators=[
                    common.field_validators.advanced_file.AdvancedFileValidator(
                        allowed_inner_types=[
                            "application/pdf",
                            "text/plain",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        allowed_types=[
                            "application/zip",
                            "application/pdf",
                            "text/plain",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        max_size=10485760,
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="presentation",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="lectures/presentations/",
                validators=[
                    common.field_validators.advanced_file.AdvancedFileValidator(
                        allowed_inner_types=[
                            "application/pdf",
                            "text/plain",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        allowed_types=[
                            "application/zip",
                            "application/pdf",
                            "text/plain",
                            "application/msword",
                            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                            "application/vnd.ms-excel",
                            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        ],
                        max_size=10485760,
                    )
                ],
            ),
        ),
    ]
